/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.tracker;

import java.awt.Color;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author shamary williams
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private javax.swing.JTextField jtf[]=new javax.swing.JTextField[5];
    
    private String uid,password;/////user id and password;
    
    public Menu(String uid,String password) {
        initComponents();
        
        Inventory.init();/////prepare inventory 
        
        this.uid=uid;
        this.password=password;
    }
    
    private void reset(javax.swing.JTextField tf[],javax.swing.JTextArea ta,javax.swing.JLabel label)//clear dialog fields
    {
        if(tf.length>0)
        {
            for(javax.swing.JTextField t : tf)
            {
               t.setText("");
            }
        }
        
        if(label!=null)
        {
            label.setText("");
        }
        
        if(ta!=null)
        {
            ta.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        item_name_label = new javax.swing.JLabel();
        item_name = new javax.swing.JTextField();
        item_id_label = new javax.swing.JLabel();
        item_id = new javax.swing.JTextField();
        qty_label = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        add_cancel = new javax.swing.JButton();
        add_submit = new javax.swing.JButton();
        add_msg = new javax.swing.JLabel();
        search_dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        search_itemID = new javax.swing.JTextField();
        search_submit = new javax.swing.JButton();
        search_cancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        showAll = new javax.swing.JButton();
        request_dialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r_itemID = new javax.swing.JTextField();
        r_qty = new javax.swing.JTextField();
        r_empID = new javax.swing.JTextField();
        r_itemName = new javax.swing.JTextField();
        r_submit = new javax.swing.JButton();
        r_cancel = new javax.swing.JButton();
        r_msg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        request = new javax.swing.JButton();
        addItem = new javax.swing.JButton();
        search = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        add_dialog.setTitle("Add Item");
        add_dialog.setIconImage(null);
        add_dialog.setMinimumSize(new java.awt.Dimension(300, 270));
        add_dialog.setModal(true);

        item_name_label.setText("Item name:");

        item_id_label.setText("Item ID:");

        qty_label.setText("Quantity:");

        add_cancel.setText("Close");
        add_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cancelActionPerformed(evt);
            }
        });

        add_submit.setText("Submit");
        add_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_submitActionPerformed(evt);
            }
        });

        add_msg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(add_submit)
                        .addGap(18, 18, 18)
                        .addComponent(add_cancel))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(qty_label)
                                .addGap(18, 18, 18)
                                .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(item_id_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_msg)
                                    .addComponent(item_id, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(item_name_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(add_msg)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_id_label)
                    .addComponent(item_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label)
                    .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qty_label)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_submit)
                    .addComponent(add_cancel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        search_dialog.setTitle("Lookup Item");
        search_dialog.setMinimumSize(new java.awt.Dimension(335, 285));
        search_dialog.setModal(true);

        jLabel5.setText("Item ID:");

        search_submit.setText("Search");
        search_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_submitActionPerformed(evt);
            }
        });

        search_cancel.setText("Close");
        search_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cancelActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        showAll.setText("Show All");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(search_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(search_submit)
                .addGap(18, 18, 18)
                .addComponent(showAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(search_cancel)
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(search_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_submit)
                    .addComponent(search_cancel)
                    .addComponent(showAll))
                .addContainerGap())
        );

        javax.swing.GroupLayout search_dialogLayout = new javax.swing.GroupLayout(search_dialog.getContentPane());
        search_dialog.getContentPane().setLayout(search_dialogLayout);
        search_dialogLayout.setHorizontalGroup(
            search_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        search_dialogLayout.setVerticalGroup(
            search_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        request_dialog.setTitle("Request Item");
        request_dialog.setMinimumSize(new java.awt.Dimension(338, 265));
        request_dialog.setModal(true);

        jLabel6.setText("Item ID:");

        jLabel7.setText("Item name:");

        jLabel8.setText("Employee ID:");

        jLabel9.setText("Quantity:");

        r_submit.setText("Submit");
        r_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_submitActionPerformed(evt);
            }
        });

        r_cancel.setText("Close");
        r_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_cancelActionPerformed(evt);
            }
        });

        r_msg.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout request_dialogLayout = new javax.swing.GroupLayout(request_dialog.getContentPane());
        request_dialog.getContentPane().setLayout(request_dialogLayout);
        request_dialogLayout.setHorizontalGroup(
            request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(request_dialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(request_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(request_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(request_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(request_dialogLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(r_submit)
                                .addGap(18, 18, 18)
                                .addComponent(r_cancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, request_dialogLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(r_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, request_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_msg)
                            .addComponent(r_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        request_dialogLayout.setVerticalGroup(
            request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(request_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r_msg)
                .addGap(5, 5, 5)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(r_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(r_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(r_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r_empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_submit)
                    .addComponent(r_cancel))
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Inventory Tracker");

        request.setText("Request item");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        addItem.setText("Add item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        search.setText("Search item");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(request)
                .addGap(18, 18, 18)
                .addComponent(addItem)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(request)
                    .addComponent(addItem)
                    .addComponent(search)
                    .addComponent(exit))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /***********************************Menu**************************************/
    
    ///////Exit
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
    
    /*********************************Add Item*******************************************/
    //////Add item dialog
    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        if(Authorization.authorize(uid, password))
        {
            this.add_dialog.setVisible(true);
        }
    }//GEN-LAST:event_addItemActionPerformed
    
    //////close add item dialog
    private void add_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cancelActionPerformed
        
        jtf=new javax.swing.JTextField[]{item_id,item_name,qty};
        reset(jtf,null,add_msg);
        
        this.add_dialog.dispose();
    }//GEN-LAST:event_add_cancelActionPerformed

    /*****************************Search**************************************/
    //////Search for item dialog
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if(Authorization.authorize(uid, password))
        {
            this.search_dialog.setVisible(true);
        }
    }//GEN-LAST:event_searchActionPerformed
    
    //////search button
    private void search_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_submitActionPerformed
        
        String res=Inventory.searchItem(search_itemID.getText());
        
        result.setText("\tRESULT\n\n"+res);
    }//GEN-LAST:event_search_submitActionPerformed

    private void search_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cancelActionPerformed
        
        jtf=new javax.swing.JTextField[]{search_itemID};
        reset(jtf,result,null);
        
        this.search_dialog.dispose();
    }//GEN-LAST:event_search_cancelActionPerformed

    
    /****************************Request************************************************/ 
    private void r_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_submitActionPerformed
        
        String result="";
        
        if(!invalid(r_empID.getText()))
        {
            if(!(result=Inventory.searchItem(r_itemID.getText())).toLowerCase().contains("not found"))////if item found
            {
                r_msg.setForeground(Color.blue);
                r_msg.setText("Request sent");

                try
                {
                    //////used to extract item name
                    int i=result.indexOf(" ");
                    int j=result.indexOf("\n");

                    if(r_itemName.getText().equals(result.substring(i+1,j)))
                    {
                        ////add request info
                        PrintWriter pw=new PrintWriter("request/"+r_empID.getText()+"_request_for_"+r_itemName.getText()+".txt");
                        pw.println("Employee ID: "+r_empID.getText());
                        pw.println("Item ID: "+r_itemID.getText());
                        pw.println("Item name: "+r_itemName.getText());
                        pw.println("request quantity: "+r_qty.getText());
                        pw.close();
                    }
                    else
                    {
                        throw new IOException();
                    }
                }
                catch(IOException io)
                {
                    io.printStackTrace();

                    r_msg.setForeground(Color.red);
                    r_msg.setText("Item not found");
                }
            }
            else
            {
                r_msg.setForeground(Color.red);
                r_msg.setText("Item not found");
            }
        }
        else
        {
            r_msg.setForeground(Color.red);
            r_msg.setText("invalid employee ID");
        }
    }//GEN-LAST:event_r_submitActionPerformed

    private void r_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_cancelActionPerformed
        
        jtf=new javax.swing.JTextField[]{r_empID,r_itemID,r_itemName,r_qty};
        reset(jtf,null,r_msg);
        
        this.request_dialog.dispose();
    }//GEN-LAST:event_r_cancelActionPerformed
    
    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        if(Authorization.authorize(uid, password))
        {
            this.request_dialog.setVisible(true);
        }
    }//GEN-LAST:event_requestActionPerformed
    /*****************************Add item***********************************************/
    
    private void add_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_submitActionPerformed
       
        try
        {
            if(!invalid(item_id.getText())&&!invalid(item_name.getText()))
            {
                if(Inventory.UpdateInvent(new ItemInfo(item_id.getText(),item_name.getText(),
                        Integer.parseInt(qty.getText()))))
                {
                    add_msg.setForeground(Color.blue);
                    add_msg.setText("Item successfully added");
                    //add_dialog.dispose();
                }
                else
                {
                    add_msg.setForeground(Color.red);
                    add_msg.setText("internal database error occured");
                }
            }
            else
            {
                add_msg.setForeground(Color.red);
                add_msg.setText("invalid data entered");
            }
            
            //add_msg.setForeground(Color.green);
            //add_msg.setText("Item successfully added");
        }
        catch(NumberFormatException nfe)
        {
            add_msg.setForeground(Color.red);
            add_msg.setText("invalid quantity entered");
        }
    }//GEN-LAST:event_add_submitActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        result.setText(Inventory.showAll());
    }//GEN-LAST:event_showAllActionPerformed
 
    
    private boolean invalid(String s)
    {  
        return (s.equals("")||s.charAt(0)==' ');
    }
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton add_cancel;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JLabel add_msg;
    private javax.swing.JButton add_submit;
    private javax.swing.JButton exit;
    private javax.swing.JTextField item_id;
    private javax.swing.JLabel item_id_label;
    private javax.swing.JTextField item_name;
    private javax.swing.JLabel item_name_label;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel qty_label;
    private javax.swing.JButton r_cancel;
    private javax.swing.JTextField r_empID;
    private javax.swing.JTextField r_itemID;
    private javax.swing.JTextField r_itemName;
    private javax.swing.JLabel r_msg;
    private javax.swing.JTextField r_qty;
    private javax.swing.JButton r_submit;
    private javax.swing.JButton request;
    private javax.swing.JDialog request_dialog;
    private javax.swing.JTextArea result;
    private javax.swing.JButton search;
    private javax.swing.JButton search_cancel;
    private javax.swing.JDialog search_dialog;
    private javax.swing.JTextField search_itemID;
    private javax.swing.JButton search_submit;
    private javax.swing.JButton showAll;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
