/*
 * Menu GUI
 */
package inventory.tracker;

import java.awt.Color;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shamary williams
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private javax.swing.JTextField jtf[]=new javax.swing.JTextField[5];
    
    private String uid,password;/////user id and password;
    
    public Menu(String uid,String password) {
        initComponents();
        
        Inventory.init(uid,password);/////prepare inventory 
        
        this.uid=uid;
        this.password=password;
    }
    
    private void reset(javax.swing.JTextField tf[],javax.swing.JTextArea ta,javax.swing.JLabel label)//clear dialog fields
    {
        if(tf.length>0)
        {
            for(javax.swing.JTextField t : tf)
            {
               t.setText("");
            }
        }
        
        if(label!=null)
        {
            label.setText("");
        }
        
        if(ta!=null)
        {
            ta.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_dialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        item_name_label = new javax.swing.JLabel();
        item_name = new javax.swing.JTextField();
        item_id_label = new javax.swing.JLabel();
        item_id = new javax.swing.JTextField();
        qty_label = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        add_cancel = new javax.swing.JButton();
        add_submit = new javax.swing.JButton();
        add_msg = new javax.swing.JLabel();
        search_dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        item_label_sd = new javax.swing.JLabel();
        search_itemID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        dTable = new javax.swing.JTable();
        search_submit = new javax.swing.JButton();
        showAll = new javax.swing.JButton();
        search_cancel = new javax.swing.JButton();
        request_dialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        r_msg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r_itemID = new javax.swing.JTextField();
        r_itemName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        r_qty = new javax.swing.JTextField();
        r_empID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        r_submit = new javax.swing.JButton();
        r_len = new javax.swing.JTextField();
        r_cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        request = new javax.swing.JButton();
        addItem = new javax.swing.JButton();
        search = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        add_dialog.setTitle("Add Item");
        add_dialog.setIconImage(null);
        add_dialog.setMinimumSize(new java.awt.Dimension(383, 330));
        add_dialog.setModal(true);
        add_dialog.setPreferredSize(new java.awt.Dimension(383, 330));
        add_dialog.setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "v1.0", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Ext", 0, 11))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 370));

        item_name_label.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        item_name_label.setText("Item name:");

        item_name.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        item_id_label.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        item_id_label.setText("Item ID:");

        item_id.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        qty_label.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        qty_label.setText("Quantity:");

        qty.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        add_cancel.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        add_cancel.setText("Close");
        add_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cancelActionPerformed(evt);
            }
        });

        add_submit.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        add_submit.setText("Submit");
        add_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_submitActionPerformed(evt);
            }
        });

        add_msg.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(qty_label)
                            .addGap(18, 18, 18)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(item_id_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(add_msg)
                                .addComponent(item_id, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(item_name_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_submit)
                .addGap(18, 18, 18)
                .addComponent(add_cancel)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(add_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_id_label)
                    .addComponent(item_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label)
                    .addComponent(item_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qty_label)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_submit)
                    .addComponent(add_cancel))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout add_dialogLayout = new javax.swing.GroupLayout(add_dialog.getContentPane());
        add_dialog.getContentPane().setLayout(add_dialogLayout);
        add_dialogLayout.setHorizontalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        add_dialogLayout.setVerticalGroup(
            add_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        search_dialog.setTitle("Lookup Item");
        search_dialog.setMinimumSize(new java.awt.Dimension(383, 330));
        search_dialog.setModal(true);
        search_dialog.setPreferredSize(new java.awt.Dimension(383, 330));
        search_dialog.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "v1.0", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Ext", 0, 11))); // NOI18N

        item_label_sd.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        item_label_sd.setText("Item ID:");

        search_itemID.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        dTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(dTable);

        search_submit.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        search_submit.setText("Search");
        search_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_submitActionPerformed(evt);
            }
        });

        showAll.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        showAll.setText("Show All");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        search_cancel.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        search_cancel.setText("Close");
        search_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(item_label_sd)
                .addGap(18, 18, 18)
                .addComponent(search_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(search_submit)
                .addGap(26, 26, 26)
                .addComponent(showAll)
                .addGap(27, 27, 27)
                .addComponent(search_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_label_sd)
                    .addComponent(search_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_submit)
                    .addComponent(search_cancel)
                    .addComponent(showAll))
                .addContainerGap())
        );

        javax.swing.GroupLayout search_dialogLayout = new javax.swing.GroupLayout(search_dialog.getContentPane());
        search_dialog.getContentPane().setLayout(search_dialogLayout);
        search_dialogLayout.setHorizontalGroup(
            search_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        search_dialogLayout.setVerticalGroup(
            search_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        request_dialog.setTitle("Request Item");
        request_dialog.setMinimumSize(new java.awt.Dimension(383, 330));
        request_dialog.setModal(true);
        request_dialog.setPreferredSize(new java.awt.Dimension(383, 330));
        request_dialog.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "v1.0", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Ext", 0, 11))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(362, 341));

        r_msg.setForeground(new java.awt.Color(0, 0, 255));
        r_msg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_msg.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        r_msg.setName(""); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel6.setText("Item ID:");

        r_itemID.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        r_itemName.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        r_itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_itemNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel7.setText("Item name:");

        jLabel9.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel9.setText("Quantity:");

        r_qty.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        r_empID.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel8.setText("Employee ID:");

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        jLabel1.setText("Request length(in days):");

        r_submit.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        r_submit.setText("Submit");
        r_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_submitActionPerformed(evt);
            }
        });

        r_len.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N

        r_cancel.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        r_cancel.setText("Close");
        r_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_empID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_len, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r_qty, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(r_itemName, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(r_itemID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r_submit)
                .addGap(18, 18, 18)
                .addComponent(r_cancel)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(r_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(r_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(r_itemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(r_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(r_empID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(r_len, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_submit)
                    .addComponent(r_cancel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout request_dialogLayout = new javax.swing.GroupLayout(request_dialog.getContentPane());
        request_dialog.getContentPane().setLayout(request_dialogLayout);
        request_dialogLayout.setHorizontalGroup(
            request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        request_dialogLayout.setVerticalGroup(
            request_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(request_dialogLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(340, 145, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "v1.0", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro Ext", 0, 11))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Quartz MS", 0, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Inventory Tracker");

        request.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        request.setForeground(new java.awt.Color(51, 51, 51));
        request.setText("Request item");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        addItem.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        addItem.setForeground(new java.awt.Color(51, 51, 51));
        addItem.setText("Add item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("Search item");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(request)
                .addGap(18, 18, 18)
                .addComponent(addItem)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(request)
                    .addComponent(addItem)
                    .addComponent(search)
                    .addComponent(exit))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /***********************************Menu**************************************/
    
    ///////Exit
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            close();
    }//GEN-LAST:event_exitActionPerformed
    
    /*********************************Add Item*******************************************/
    //////Add item dialog
    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        if(Authorization.authorize(uid, password))
        {
            this.add_dialog.setVisible(true);
        }
    }//GEN-LAST:event_addItemActionPerformed
    
    /*****************************Search**************************************/
    //////Search for item dialog
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if(Authorization.authorize(uid, password))
        {
            clearTable();
            this.search_dialog.setVisible(true);
        }
    }//GEN-LAST:event_searchActionPerformed
    
    //////search button
    private void search_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_submitActionPerformed
        
        clearTable();
        
        String res=Inventory.searchItem(search_itemID.getText());
        DefaultTableModel table=getModel();
        
        String[] row=res.split("\t");
        table.addRow(row);
        
        //result.setText("\tRESULT\n\nName\tQuantity\n\n"+res);
    }//GEN-LAST:event_search_submitActionPerformed

    private void search_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cancelActionPerformed
        
        jtf=new javax.swing.JTextField[]{search_itemID};
        reset(jtf,null,null);
        
        clearTable();
        
        this.search_dialog.dispose();
    }//GEN-LAST:event_search_cancelActionPerformed

        
    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        if(Authorization.authorize(uid, password))
        {
            this.request_dialog.setVisible(true);
        }
    }//GEN-LAST:event_requestActionPerformed
    /*****************************Add item***********************************************/
    
    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        //result.setText(Inventory.showAll());
        clearTable();
        
        DefaultTableModel table=getModel();
        
        String[] seg=Inventory.showAll().split(System.lineSeparator());
        
        for(String s:seg)
        {
            String[] row=s.split("\t");
            
            table.addRow(row);
        }
    }//GEN-LAST:event_showAllActionPerformed

    private void r_itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_itemNameActionPerformed

    private void add_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_submitActionPerformed

        try
        {
            if(!invalid(item_id.getText())&&!invalid(item_name.getText()))
            {
                ItemInfo item=new ItemInfo(item_id.getText(),item_name.getText(),Integer.parseInt(qty.getText()));

                if(Inventory.searchItem(item.getID()).toLowerCase().contains(item_name.getText()))////search if item already in database
                {
                    if(Inventory.update(item.getID(),item.getQty()))
                    {
                        add_msg.setForeground(Color.blue);
                        add_msg.setText("Item successfully added");
                    }
                    else
                    {
                        add_msg.setForeground(Color.red);
                        add_msg.setText("Item failed to update");
                    }

                    System.out.println("item found");
                }
                else if(Inventory.UpdateInvent(item))
                {
                    add_msg.setForeground(Color.blue);
                    add_msg.setText("Item successfully added");
                    //add_dialog.dispose();
                }
                else
                {
                    add_msg.setForeground(Color.red);
                    add_msg.setText("internal database error occured");
                }
            }
            else
            {
                add_msg.setForeground(Color.red);
                add_msg.setText("invalid data entered");
            }

            //add_msg.setForeground(Color.green);
            //add_msg.setText("Item successfully added");
        }
        catch(NumberFormatException nfe)
        {
            add_msg.setForeground(Color.red);
            add_msg.setText("invalid quantity entered");
        }
    }//GEN-LAST:event_add_submitActionPerformed

    //////close add item dialog
    private void add_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cancelActionPerformed

        jtf=new javax.swing.JTextField[]{item_id,item_name,qty};
        reset(jtf,null,add_msg);

        this.add_dialog.dispose();
    }//GEN-LAST:event_add_cancelActionPerformed

    private void r_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_cancelActionPerformed

        jtf=new javax.swing.JTextField[]{r_empID,r_itemID,r_itemName,r_qty};
        reset(jtf,null,r_msg);

        this.request_dialog.dispose();
    }//GEN-LAST:event_r_cancelActionPerformed

    /****************************Request************************************************/ 
    private void r_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_submitActionPerformed

        String result="";

        if(!invalid(r_empID.getText())&&Integer.parseInt(r_qty.getText())>0)
        {
            if(!(result=Inventory.searchItem(r_itemID.getText())).toLowerCase().contains("not found") &&
                Inventory.getQty(r_itemID.getText())>Integer.parseInt(r_qty.getText()))////if item found
            {
                r_msg.setForeground(Color.blue);
                r_msg.setText("Request sent");

                try
                {
                    //////used to extract item name
                    //int i=result.indexOf(" ");
                    //int j=result.indexOf("\n");

                    String[] seg=result.split("\t");
                    
                    if(r_itemName.getText().equals(seg[1]))
                    {
                        new EmployeeInfo(r_empID.getText()).requestItem(new ItemInfo(r_itemID.getText(),
                            r_itemName.getText(),Integer.parseInt(r_qty.getText()),Integer.parseInt(r_len.getText())));
                    }
                    else
                    {
                        throw new IOException();
                    }
            }
            catch(IOException io)
            {
                io.printStackTrace();

                r_msg.setForeground(Color.red);
                r_msg.setText("Request error (invalid item name)");
            }
            catch(Exception e)
            {
                e.printStackTrace();

                r_msg.setForeground(Color.red);
                r_msg.setText("Request error");
            }
        }
        else
        {
            r_msg.setForeground(Color.red);
            r_msg.setText("Request error (item not found or invalid duration)");
        }
        }
        else
        {
            r_msg.setForeground(Color.red);
            r_msg.setText("invalid employee ID");
        }
    }//GEN-LAST:event_r_submitActionPerformed
 
    /*
    private int get_cur_qty(String res)///get current quantity of an item
    {
        int i=res.indexOf("\t");
        
        int qi=res.indexOf("\t",i);
        
        System.out.println(res.substring(i));
        try
        {
            return Integer.parseInt(res.substring(qi+1));
        }
        catch(NumberFormatException e)
        {
            e.printStackTrace();
        }
        
        return 0;
    }*/
    
    private boolean invalid(String s)///check for invalid string
    {  
        return (s.equals("")||s.charAt(0)==' ');
    }
    
    private void close()
    {
        System.exit(0);
    }
    
    private DefaultTableModel getModel()
    {
        return (DefaultTableModel)dTable.getModel();
    }
    
    private void clearTable()
    {
        for(int i=getModel().getRowCount()-1;i>-1;i--)
        {
            getModel().removeRow(i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton add_cancel;
    private javax.swing.JDialog add_dialog;
    private javax.swing.JLabel add_msg;
    private javax.swing.JButton add_submit;
    private javax.swing.JTable dTable;
    private javax.swing.JButton exit;
    private javax.swing.JTextField item_id;
    private javax.swing.JLabel item_id_label;
    private javax.swing.JLabel item_label_sd;
    private javax.swing.JTextField item_name;
    private javax.swing.JLabel item_name_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel qty_label;
    private javax.swing.JButton r_cancel;
    private javax.swing.JTextField r_empID;
    private javax.swing.JTextField r_itemID;
    private javax.swing.JTextField r_itemName;
    private javax.swing.JTextField r_len;
    private javax.swing.JLabel r_msg;
    private javax.swing.JTextField r_qty;
    private javax.swing.JButton r_submit;
    private javax.swing.JButton request;
    private javax.swing.JDialog request_dialog;
    private javax.swing.JButton search;
    private javax.swing.JButton search_cancel;
    private javax.swing.JDialog search_dialog;
    private javax.swing.JTextField search_itemID;
    private javax.swing.JButton search_submit;
    private javax.swing.JButton showAll;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
